name: Deploy to CF Pages in Production

on:
  push:
    branches:
      - prod  # Adjust this to your source branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: The-Economic-Journal-Dev/the-economic-journal-frontend  # Replace with your repo name
        ref: prod

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Checkout deployment repository
      uses: actions/checkout@v3
      with:
        repository: The-Economic-Journal-Dev/cf-pages
        token: ${{ secrets.PAT }}
        path: cf-pages
        
    - name: Install tree
      run: sudo apt-get install -y tree
      
    - name: Copy files to deployment repository
      run: |
        mkdir -p cf-pages/dist
        rm -rf cf-pages/dist/* || true
        cp -rf dist cf-pages/
      working-directory: ${{ github.workspace }}

    - name: Check for file changes
      run: |
        cd cf-pages
        git diff --stat

    - name: List untracked files
      run: |
        cd cf-pages
        git ls-files --others --exclude-standard

    - name: Display cf-pages directory structure
      run: tree -L 3 cf-pages

    - name: Commit and push changes
      run: |
        cd cf-pages
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Deploy updated site"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.PAT }}
